### ISSUE TITLE
Don't show warnings for supplies that aren't needed on a vessel

### ISSUE THREAD

**Issue by SirMortimer** [Kerbalism/Kerbalism#434]
> "Having a rocket warn you that it's almost out of lox isn't that useful when it's meant to be out of lox because you're burning it."

RO has a lot of different process configs for a lot of different life support setups that they have. One of them probably uses LOX as an input resource for life support, so there is a Resource config for LOX.

Kerbalism runs ALL resources on ALL vessels, regardless of wether there is a process present on the vessel that actually needs or produces the resource. So, when you burn up LOX in your engine on a vessel that carries nothing but a probe core, you get a warning because there exists an Apollo style life support module that isn't even installed on the vessel.

**Comment by gotmachine** [comment]
I don't see any way to prevent that. 

And I don't really see the issue, the only potential consequence is that the notification will stop timewarp, and that can't happen when you are using an engine. Unless you are in physic-warp. We could eventually not stop physic warp on notifications.

**Comment by SirMortimer** [comment]
My first instinct would be to prevent this by not running non-existing processes on a vessel. Keep track of which process needs to run where and put the warning code into the process execution. This even might help improving performance by not wasting CPU cycles.

**Comment by gotmachine** [comment]
But processes are far from the the only consumers. There are all the things that do direct calls to `Consume()`, rules and of course stock/other mods modules. I recently added to the supply data in vesseldata the list of all consumers/producers, but I don't think we can even leverage that. And that list put all the non-kerbalism producers in a single entry, as we can't know where the consumption is coming from in that case.

I mean, the root problem to me is that some resources should not be notified about, *on vessels where the resource is not critical*. I don't see a way for the code to evaluate that without feeding it with more information. We could put a `IsCritical=true/false` setting on all *consumer* processes, rules and Consume() callers (same way that we acquire the `broker name`), and only show the message if IsCritical is true for at least one broker for each resource. 

But again I don't really see the issue. Quick solution is to not put messages in the supply config entry for LOX. It seems to me that this is a very corner-case situation.

I'm far more annoyed by the planner always showing all supplies even if there is no resource capacity, no consumer and no producer.

As for not running non-existing processes for saving CPU cycles, it's already a near no-op. The only thing that's done for non existing processes is modifier evaluation, which translate to a handfull of double multiplications and a pair of value-getting on a dictionnary. There are far more concerning things regarding performance in the current codebase.

**Comment by SirMortimer** [comment]
Is this fixed in dev?

**Comment by gotmachine** [comment]
Since we still don't know what the exact issue is, nor what is needed to fix it... no...
Going back to initial problem :
> "Having a rocket warn you that it's almost out of lox isn't that useful when it's meant to be out of lox because you're burning it."

It would be a big mess to have supply messages visibility depend on what is consuming the resource, it would require a per supply configuration for every possible consumer.

And anyway the issue isn't only messages, supply work under the assumption is that "full = good" and "empty = bad". This materialize in two ways :
- Timewarp stopping supply messages when low threshold and empty threshold are reached
- Monitor supply icon and tooltip info turns red

In our example, I think the main reason lox has been defined as a supply is to have it in the Kerbalism UI, the "warn when empty" part isn't really needed or desirable. If you're running lox fuel cells, you will get warned and warp stopped when EC is low anyway.

While messages are disabled if not specified (which should be the first fix to that issue), there is still the other warnings in the UI. So, here is my proposition : 
- add a `lowLevelIndicators` bool to the configs, when set to false we don't show any level based warning in the telemetry/monitor UI.
- add `lowSeverity`, `emptySeverity` and `refillSeverity` fields, default to `warning` / `danger` /  `relax` Allow to invert the assumption to "empty = good", "full = bad".
- add `lowStopWarp`, `emptyStopWarp` and `refillStopWarp` fields, default to false. There are actually very few resources that justify stopping warp : EC, water, food, oxygen, that's it.
- while we're at it, un-hardcode the "only trigger messages if the vessel is manned" rule trough a `warnOnlyIfManned` config bool.

**Comment by Tahvohck** [comment]
I'm not completely up to date on 4.0 progress, but all of these settings should have a way to be configured pre-flight if possible. For reusable things like planes, having Kerbalism tell me that I'm low on CO2 on the runway gets old real fast.
